# Generated by Django 3.2.4 on 2022-08-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuits',
            options={'ordering': ('id',), 'verbose_name': '套件信息', 'verbose_name_plural': '套件信息'},
        ),
    ]
