# Generated by Django 3.2.4 on 2022-08-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ('id',), 'verbose_name': '测试报告', 'verbose_name_plural': '测试报告'},
        ),
    ]
