# Generated by Django 3.2.4 on 2022-08-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debugtalks',
            options={'ordering': ('id',), 'verbose_name': 'debugtalk.py文件', 'verbose_name_plural': 'debugtalk.py文件'},
        ),
    ]
